// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUL0N3yF-Mc4djpPydfHDLKu4fS7dvMLE',
    appId: '1:637325872372:web:dd427d27ecdfd054fee2a1',
    messagingSenderId: '637325872372',
    projectId: 'mytrainingsapp-aec89',
    authDomain: 'mytrainingsapp-aec89.firebaseapp.com',
    storageBucket: 'mytrainingsapp-aec89.firebasestorage.app',
    measurementId: 'G-HQY3EDVRYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4LUod50RsjZbBuzlaXsH2PzhVNxIVdXw',
    appId: '1:637325872372:android:11422caf458ce08cfee2a1',
    messagingSenderId: '637325872372',
    projectId: 'mytrainingsapp-aec89',
    storageBucket: 'mytrainingsapp-aec89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwP-6TLOj3q2s_nRkTSsZEJupoGcMaDf0',
    appId: '1:637325872372:ios:97a0b18ccdd1fbcbfee2a1',
    messagingSenderId: '637325872372',
    projectId: 'mytrainingsapp-aec89',
    storageBucket: 'mytrainingsapp-aec89.firebasestorage.app',
    iosBundleId: 'com.mytrainingsapp.mytrainingsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwP-6TLOj3q2s_nRkTSsZEJupoGcMaDf0',
    appId: '1:637325872372:ios:97a0b18ccdd1fbcbfee2a1',
    messagingSenderId: '637325872372',
    projectId: 'mytrainingsapp-aec89',
    storageBucket: 'mytrainingsapp-aec89.firebasestorage.app',
    iosBundleId: 'com.mytrainingsapp.mytrainingsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUL0N3yF-Mc4djpPydfHDLKu4fS7dvMLE',
    appId: '1:637325872372:web:ee82707f862f3e04fee2a1',
    messagingSenderId: '637325872372',
    projectId: 'mytrainingsapp-aec89',
    authDomain: 'mytrainingsapp-aec89.firebaseapp.com',
    storageBucket: 'mytrainingsapp-aec89.firebasestorage.app',
    measurementId: 'G-NT2WSB62C7',
  );
}
